#!/bin/bash
set -e
set -x

# Tar file
# for example
# 20220420T130530Z_da3c848dfa5e8269b4cd7da91ba32025b268f1d8.tar.gz
datafile=$1

# Download to AWS 
export AWS_ACCESS_KEY_ID=<AWS_ACCESS_KEY_ID>
export AWS_SECRET_ACCESS_KEY=<AWS_SECRET_ACCESS_KEY>
pip3 --no-cache-dir install --upgrade awscli
aws s3api get-object --bucket mlse.frameworks --key pytorch/unit_test_audit/${datafile} ${datafile}
tar -xf ${datafile}

set +x
