#!/bin/bash
set -e
set -x

# Tar file
datafile=$1
tar -cvzf ${datafile}.tar.gz $datafile

# Upload to AWS
pip3 --no-cache-dir install --upgrade awscli
aws --region=us-east-2 s3 cp ${datafile}.tar.gz s3://mlse.frameworks/pytorch/unit_test_audit/

set +x
